add_newline = false
command_timeout = 600
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
([($git_branch$git_commit$git_status)](bg:green cyan)[](green))\
$git_state\
$git_metrics\
$hg_branch\
$memory_usage\
$env_var\
$custom\
$sudo\
$line_break\
$battery\
$time\
$shell """

right_format = """
[](black)\
$character\
$status\
$jobs\
([$kubernetes$docker_context$package$cmake$cobol$container$dart$deno$crystal$dotnet$elixir$elm$erlang$golang$haskell$helm$java$julia$kotlin$lua$nim$nodejs$ocaml$perl$php$pulumi$purescript$python$rlang$red$ruby$rust$scala$swift$terraform$vlang$vagrant$zig$nix_shell$conda$aws$gcloud$openstack$azure](bg:black))\
$cmd_duration
"""

[battery]
disabled = true

[character]
success_symbol = "[ ✔ ](bold green bg:black)"
error_symbol = "[ ✘ ](bold red bg:black)"
format = "$symbol"

[line_break]
disabled = true

[jobs]
symbol = ""
style = "cyan bg:black"
format = "[ $symbol ]($style)"

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "

[cmd_duration]
style = "bg:yellow black"
format = "([](yellow bg:black)[ $duration  ]($style))"

[dart]
symbol = " "

[directory]
read_only = ""
style = "bg:cyan fg:white bold"
read_only_style = "fg:bright-white bg:cyan"
# [](fg:cyan)
format = "[( $read_only)]($read_only_style)[ $path ]($style)"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "fg:black bg:green"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:black bg:yellow"
format = '([ $all_status$ahead_behind ]($style))'
deleted = "!"

[git_commit]
style = "black bg:green"
format = "[[@](white bg:green)$hash$tag ]($style)"

[golang]
symbol = " "
format = " [$symbol($version )]($style)"
version_format = "${major}.${minor}"
style = "bold cyan bg:black"

[haskell]
symbol = " "
style = "bold purple bg:black"

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = " [$symbol($version )]($style)"
version_format = "${major}"
style = "bold green bg:black"

[package]
symbol = " "
format = " [$symbol$version]($style) "
disabled = true

[perl]
symbol = " "

[php]
symbol = ""
style = "147 bold bg:black"
format = "[$symbol($version )]($style)"

[python]
symbol = " "
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "yellow bold bg:black"
version_format = "${major}.${minor}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[status]
disabled = false
style = "bold red bg:black"
format = "[$status ]($style)"

[terraform]
symbol = "tf "
style = "bg:black bold 105"
