theme = "onelight"

[editor]
auto-completion = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
