call plug#begin()
Plug 'RRethy/vim-illuminate'
call plug#end()

syntax on
set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set backspace=indent,eol,start
inoremap {<cr> {<cr>}<c-o><s-o>
inoremap [<cr> [<cr>]<c-o><s-o>
inoremap (<cr> (<cr>)<c-o><s-o>

"skeletons
autocmd BufNewFile  *.py      0r ~/dotfiles/vim/skeletons/skeleton.py
autocmd BufNewFile  *.sh      0r ~/dotfiles/vim/skeletons/skeleton.sh
autocmd BufNewFile  main.go   0r ~/dotfiles/vim/skeletons/main.go
