set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'dracula/vim'
Plugin 'RRethy/vim-illuminate'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set backspace=indent,eol,start
inoremap {<cr> {<cr>}<c-o><s-o>
inoremap [<cr> [<cr>]<c-o><s-o>
inoremap (<cr> (<cr>)<c-o><s-o>

"skeletons
autocmd BufNewFile  *.py      0r ~/dotfiles/vim/skeletons/skeleton.py
autocmd BufNewFile  *.sh      0r ~/dotfiles/vim/skeletons/skeleton.sh
